### ISSUE TITLE
BrowserFS Deprecated

### ISSUE THREAD

**Issue by james-pre** [yamachig/Lawtext#1]
Hi there, I'm a maintainer of BrowserFS. I've been going though the [dependents](https://www.npmjs.com/package/browserfs?activeTab=dependents) of BrowserFS.

Please see the notice in the readme: https://github.com/jvilk/browserfs

Would you be interested in updating your project to use the updated fork, [ZenFS](https://github.com/zen-fs/core)?

**Comment by james-pre** [comment]
@yamachig  Any updates on this?

**Comment by yamachig** [comment]
@james-pre Hi! Thank you for the reminder. Actually, the current Lawtext version does not depend on BrowserFS, so I will review the package.json and remove the dependencies. Thanks!
